name: Download from Kaggle and Upload to ADLS

on:
#   push:
#     branches:
#       - main
#       - feature/*
  workflow_dispatch:

jobs:
  data-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # 🔹 Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 🔹 Install dependencies
    - name: Install Kaggle CLI
      run: pip install kaggle

    # 🔹 Configure Kaggle
    - name: Setup Kaggle API
      run: |
        mkdir -p ~/.kaggle
        echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    # 🔹 Download dataset
    - name: Download dataset
      run: |
        kaggle datasets download -d ninadmehendale/multimodal-iris-fingerprint-biometric-data
        unzip -o multimodal-iris-fingerprint-biometric-data.zip -d data

    # 🔹 Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 🔹 Upload to ADLS
    - name: Upload to ADLS
      run: |
        az storage blob upload-batch \
          --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
          --destination ${{ vars.AZURE_STORAGE_CONTAINER }} \
          --source ./data \
          --overwrite true \
          --auth-mode login \
          --query "{count: length([]), size_gb: sum([].properties.contentLength) / 1024 / 1024 / 1024}"
